name: test-go-sockets
base: core20
adopt-info: server
summary: test go socket activation with snaps
description: test go socket activation with snaps

grade: stable
confinement: strict

hooks:
  install:
    plugs:
      - network

system-usernames:
  snap_daemon: shared

apps:
  daemon:
    command: bin/server
    command-chain:
      - bin/drop-snap-daemon.sh
    daemon: simple
    plugs:
      - network-bind
      - network
    sockets:
      http:
        listen-stream: 80

parts:
  local-assets:
    source: snap/local
    plugin: dump
  server:
    build-environment:
      - CGO_ENABLED: "0"
    plugin: go
    source: .
    build-packages:
      - git
    stage-packages:
      - curl
      - util-linux
    override-build: |
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin
      cd $SNAPCRAFT_PART_SRC
      snapcraftctl set-version $(git describe --tags --always --dirty)
      go build -o $SNAPCRAFT_PART_INSTALL/bin ./...
